### ISSUE TITLE
部屋内ニックネームが味気ない

### ISSUE THREAD

**Issue by Yuki-Inamoto** [Hironsan/Brain_Hacker#16]
ニックネームを「user2」ではなく、ランダムに「猫」とか「犬」のように、あるカテゴリの中のランダムな名前にしたい

**Comment by Hironsan** [comment]
RoomSocketHandlerのjoinRoomかinitClientで割り当てるのが楽だと思う。

**Comment by ykoga-kyutech** [comment]
以下のようなコードをChatクラスに入れて、動作確認しました。
例えば、
・青りんご
・金メロン
・茶バナナ
のような名前がユーザのニックネームとして割り振られます。
色10種類、果物10種類あるので10*10=100通りの名前が出来ます。
ただ、このコードをChatクラスにそのまま突っ込んでよいのか迷ったので（特に色と果物の定義部分）pull requestは送っていません。

```
import itertools
colors = ['赤', '青', '黄', '緑', '紫', '黒', '茶', '灰色', '金', '銀']
fruits = ['りんご', 'みかん', 'メロン', 'パイナップル', 'ぶどう', '梨', 'いちご', 'もも', 'さくらんぼ', 'バナナ']
fruits_with_color = itertools.product(colors, fruits)
user_name = list(map(lambda n:n[0]+n[1], fruits_with_color))
random.shuffle(user_name)
```

**Comment by Hironsan** [comment]
わかりやすくなりました。
