### ISSUE TITLE
付箋の色を自分で選べる

### ISSUE THREAD

**Issue by Yuki-Inamoto** [Hironsan/Brain_Hacker#19]
付箋の色は現在ランダムに選ばれているので、自分たちで選べるようにしたい

**Comment by Hironsan** [comment]
今は、script.jsのrandomCardColourで選択している。
部屋に入った段階で、サーバーから色を割り振るのが、一番管理が楽な方法だと思う。
RoomSocketHandlerのjoinRoomかinitClientで割り振る。

**Comment by ko-he-** [comment]
選べる4種類のボタンを追加

**Comment by Hironsan** [comment]
動作確認終了
