### ISSUE TITLE
部屋の中にいる人数が知りたい

### ISSUE THREAD

**Issue by Yuki-Inamoto** [Hironsan/Brain_Hacker#20]
ブレスト部屋の中にいる人数が表示できたらうれしい

**Comment by Hironsan** [comment]
Roomsクラスに人数取得用のメソッドを作ればできる。

**Comment by ko-he-** [comment]
変更箇所
room_handler.py, rooms.py

変更理由
ブレスと画面での在席人数を表示するため。

変更
room_handler.join_room, room_handler.on_close, rooms.count_user_already_in_room_of


デザインの修正はまだ

**Comment by ko-he-** [comment]
ボード内に表示されるよう変更しました。

**Comment by Hironsan** [comment]
Congratulations!
