### ISSUE TITLE
ブレスト画面のデザインが暗い

### ISSUE THREAD

**Issue by Hironsan** [Hironsan/Brain_Hacker#22]
もっとカラフルで、楽しげなデザインになると創造力が爆発すると思う。

**Comment by ko-he-** [comment]
変更箇所
style.css

変更理由
ブレインストーミング画面のデザインが他画面と統一されていないため

変更
背景色など


全体的に色合いを変更。

**Comment by ko-he-** [comment]
変更は以上の予定

**Comment by Hironsan** [comment]
素晴らしい！
